name: Deploy to Self-Hosted NGINX Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to NGINX
    runs-on: self-hosted

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to NGINX
      run: |
       cd ~
        echo "hello from nafiz" >> test.txt
